import * as cdk from "aws-cdk-lib";
import { Template, Match } from "aws-cdk-lib/assertions";

import { EnvName } from "../../../enums/EnvName";
import * as JanushAutoGeneratedApp from "../../../lib/janush-auto-generated-app-stack";

describe("Application stack [Email]", () => {
  const app = new cdk.App();
  const stack = new JanushAutoGeneratedApp.JanushAutoGeneratedAppStack(
    app,
    "MyTestStack",
    {
      envName: EnvName.Development,
    }
  );

  const template = Template.fromStack(stack);

  it("should have specific S3 Bucket resource", () => {
    template.hasResource("AWS::S3::Bucket", {
      Properties: {
        Tags: Match.arrayWith([
          {
            Key: "ResourcePurpose",
            Value: "Authentication",
          },
        ]),
      },
      UpdateReplacePolicy: "Delete",
      DeletionPolicy: "Delete",
    });
  });

  it("should have specific Lambda resource", () => {
    template.hasResource("AWS::Lambda::Function", {
      Properties: {
        Runtime: "nodejs14.x",
        Tags: Match.arrayWith([
          {
            Key: "ResourcePurpose",
            Value: "Authentication",
          },
        ]),
      },
    });
  });
});
